INSERT INTO organizations (name, description, image_path)
VALUES
('Alianza para la Acción Climática Venezuela', 'Organización dedicada a abordar los desafíos del cambio climático en Venezuela a través de la sensibilización, la promoción de políticas ambientales y la movilización ciudadana', ''),
('ACOANA', 'Asociación Civil de conservación y protección del ambiente en Venezuela, enfocada en la conservación de la biodiversidad y la educación ambiental', ''),
('Agroclima Venezuela', 'ONG que trabaja en la intersección entre la agricultura sostenible y el cambio climático, promoviendo prácticas agrícolas resilientes y amigables con el medio ambiente', ''),
('Asociación Civil Acción Campesina', 'Organización que apoya a las comunidades rurales y campesinas en Venezuela, promoviendo la seguridad alimentaria, el desarrollo rural y la equidad', ''),
('Caritas de Venezuela', 'Organización humanitaria de la Iglesia Católica que brinda asistencia a comunidades vulnerables en áreas como alimentación, salud y educación', ''),
('Clima21 - Ambiente y Derechos Humanos', 'ONG que trabaja en la intersección entre el cambio climático y los derechos humanos, abogando por políticas ambientales justas y sostenibles', ''),
('Colectivo de Montañismo Ecológico Tatuy', 'Grupo que promueve el montañismo responsable y la conservación de los ecosistemas de montaña en Venezuela', ''),
('Comitato Internazionale Per Lo Sviluppo Dei Popoli (CISP)', 'Organización internacional que trabaja en el desarrollo comunitario y la cooperación internacional en áreas diversas, incluyendo Venezuela', ''),
('Eposak', 'ONG que se enfoca en la conservación y protección de especies en peligro de extinción en Venezuela', ''),
('Fundación Agua Clara', 'Organización que trabaja en la protección y gestión sostenible de los recursos hídricos en Venezuela', ''),
('Fundación Azul Ambientalistas', 'ONG dedicada a la conservación y restauración de ecosistemas acuáticos y marinos en Venezuela', ''),
('Fundación Caribe Sur', 'Organización que trabaja en la conservación de los recursos naturales y la promoción del desarrollo sostenible en la región del Caribe venezolano', ''),
('FUDENA', 'Fundación para la Defensa de la Naturaleza, enfocada en la conservación ambiental, el desarrollo sostenible y la educación', ''),
('Fundación El Zulia Recicla', 'ONG que promueve la cultura del reciclaje y la gestión adecuada de los residuos en el estado Zulia', ''),
('Fundación Reusamas', 'Organización que se dedica al reciclaje y la reutilización de materiales para promover la sustentabilidad', ''),
('Fundación Tierra Viva', 'ONG que trabaja en la promoción de la agroecología, la soberanía alimentaria y la conservación de la biodiversidad', ''),
('Geografía Viva', 'Organización que aboga por la justicia social, la equidad y la participación ciudadana en Venezuela', ''),
('Grupo Social CESAP', 'Organización que aboga por la justicia social, la equidad y la participación ciudadana en Venezuela', ''),
('La Tierra se Calienta', 'ONG que se dedica a la sensibilización y educación sobre el cambio climático y sus impactos', ''),
('Instituto Venezolano de Estudios Sociales y Políticos (INVESP)', 'Organización enfocada en la investigación y análisis de temas sociales y políticos en Venezuela', ''),
('Phynatura, Asociación civil', 'ONG que promueve la educación y conservación ambiental a través de programas educativos y proyectos comunitarios', ''),
('Provita', 'Organización dedicada a la conservación de la biodiversidad venezolana a través de la investigación, la educación y la participación comunitaria', ''),
('Sociedad de Ciencias Naturales La Salle (SCNLS)', 'Organización que promueve el estudio y la conservación de la naturaleza a través de la investigación científica', ''),
('Todos por el Futuro', 'ONG que busca promover la sostenibilidad y el desarrollo integral en Venezuela a través de proyectos y programas comunitarios', ''),
('VerdelaTierra, A.C.', 'Organización que trabaja en la educación ambiental, la reforestación y la promoción de prácticas sostenibles', ''),
('Vitalis, A.C.', 'ONG que se enfoca en la conservación y restauración de ecosistemas naturales en Venezuela', ''),
('Wataniba, Grupo de Trabajo Socioambiental', 'Organización que trabaja con comunidades indígenas en la conservación de sus territorios y la promoción de sus derechos socioambientales', '');
