version: '3'
networks:
    fundease:


services:
    app:
        build:
            context: ./
        ports:
            - "3001:80"
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
        networks:
            - fundease
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            TZ: ${APP_TZ}
        volumes:
            - './sail-mysql:/var/lib/mysql'
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
        networks:
            - fundease
